### ISSUE TITLE
global-page-break-lines-mode not worked with browse-kill-ring

### ISSUE THREAD

**Issue by zw963** [purcell/page-break-lines#10]
Following code is not work. we still see `^L` in browse-kill-ring buffer.

```cl
(require 'page-break-lines)
(global-page-break-lines-mode 1)

;; ------------------------------ secondary  ------------------------------
;; kill-ring增强, 会自动尝试 require second-sel.
(require 'browse-kill-ring+)
(setq browse-kill-ring-separator "\f")
```

Thanks.

**Comment by purcell** [comment]
You probably need to customize the "page-break-lines-modes” variable, or use something like (add-hook ‘browse-kill-ring-mode-hook 'page-break-lines-mode).

**Comment by zw963** [comment]
> You probably need to customize the "page-break-lines-modes” variable, or use something like (add-hook ‘browse-kill-ring-mode-hook 'page-break-lines-mode).

I know this solution is work,  I just wonder why this config is worked in your's dofiles,
though i see now.  from here. https://github.com/purcell/emacs.d/blob/master/lisp/init-editing-utils.el#L102-L103

Thanks

**Comment by purcell** [comment]
Yeah, exactly, that's personal config. :-)
