### ISSUE TITLE
Don't allow page-break-lines in strings

### ISSUE THREAD

**Issue by arzoriac** [purcell/page-break-lines#14]
If there is a ^L inside a string, page-break-lines will turn it into a line.

<img width="788" alt="screen shot 2017-02-15 at 17 56 50" src="https://cloud.githubusercontent.com/assets/22227390/22992885/2afb439e-f3a8-11e6-8550-91259da25842.png">

**Comment by Compro-Prasad** [comment]
It would be better to only show the lines when the page break is on a separate line.

**Comment by purcell** [comment]
Yup, I think that's a consequence of using display tables to implement this, and it's not something that's straightforward to address, so I'm going to decline to do so. :-)
