### ISSUE TITLE
visual glitch when used with native line numbers in emacs master

### ISSUE THREAD

**Issue by CSRaghunandan** [purcell/page-break-lines#16]
I recently compiled emacs master build which contains the native line numbers implemented by Eli Zaretski. I gave it a shot and found a visual glitch with `page-break-lines-mode`. Please refer to the screenshot below:

<img width="930" alt="screen shot 2017-07-11 at 12 49 12 am" src="https://user-images.githubusercontent.com/5226809/28035600-da084c3c-65d2-11e7-9edd-88e39567a031.png">

**Comment by purcell** [comment]
Thanks. I guess that `window-width` still reports the full window width with this mode, whereas with `linum-mode` is just reports the usable width. Should be something I can patch, but before I investigate that might I suggest you ask on the list whether this difference is expected?

**Comment by CSRaghunandan** [comment]
Maybe you can use `line-number-display-width` which will return the width of the line number window?

**Comment by purcell** [comment]
Maybe. I don't currently have a HEAD version of Emacs available, and don't have time to dig into this just yet, so if you want to propose a change that works for you and will still work with older Emacs versions, I'd be happy to integrate it.

**Comment by CSRaghunandan** [comment]
I do not use line numbers myself and presently, I do not have the time to contribute a patch. Maybe someone else more capable will fix the issue :) I'm a noob with elisp

**Comment by kaushalmodi** [comment]
@CSRaghunandan It might be best to file a bug report about this. You don't have to provide a patch. Just list the steps starting with `emacs -Q`..

1. Start `emacs -Q`.
2. Clone this repo: https://github.com/purcell/page-break-lines
3. Load this package, enable line numbers, etc. to get to the visual bug you are seeing. and also reference this thread in that bug report.
