### ISSUE TITLE
The line overflows by a few characters

### ISSUE THREAD

**Issue by Compro-Prasad** [purcell/page-break-lines#17]
This happens when I am using `display-line-numbers-mode` on Emacs 27. Isn't there better heuristic to calculate the current line length in any circumstance?

**Comment by purcell** [comment]
Odd. It works fine for me with Emacs 27 and display-line-numbers-mode. Can you provide a screenshot and steps to reproduce, please?

**Comment by Compro-Prasad** [comment]
Oh. Sorry, it was a problem with spacemacs. You might want to look for https://github.com/syl20bnr/spacemacs/pull/11047
