### ISSUE TITLE
How to enable in zone mode?

### ISSUE THREAD

**Issue by sorenbug** [purcell/page-break-lines#23]
My dashboard looks like this:
![image](https://user-images.githubusercontent.com/7751296/59004269-e9ad3980-87cd-11e9-8176-e9f2f3a17fd2.png)
But as soon as I zone out the lines disable:
![image](https://user-images.githubusercontent.com/7751296/59004304-05b0db00-87ce-11e9-8ab7-4c245f19b0a7.png)
I've tried
```elisp
(push 'zone page-break-lines-modes)
```
with no avail.

How can I get these lines to still work even if I zone out?

**Comment by purcell** [comment]
`zone` doesn't define a proper major mode with hooks, so there's no neat way to do this, sorry: essentially the `page-break-lines-global-mode` trigger function will never be called by Emacs in the new buffers that the `zone` function creates, and there's no way to hook into those new buffers.

**Comment by purcell** [comment]
Actually, there's probably the option of a really gross hack involving idle timers that would look to see if zone is active and activate page-break-lines-mode in the corresponding buffer(s), but that's beyond the scope of this package.

**Comment by sorenbug** [comment]
@purcell Should I open an issue in emacs requesting zone to be hookable?

**Comment by purcell** [comment]
Yes, I think that would be a good idea.
