### ISSUE TITLE
The length of the line is only show half

### ISSUE THREAD

**Issue by taigacute** [purcell/page-break-lines#24]
Hi, i am new come to emacs. but i got some problem when i use dashboard , i found the length of the line only show half. i found dashboard use the page-break-lines. so  should i ask in here?
please see this pic .

![image](https://user-images.githubusercontent.com/41671631/62629559-f2ea8c00-b95f-11e9-859e-7822d480f3d7.png)

**Comment by purcell** [comment]
I haven't seen this behaviour before. I feel like it must be due to something `dashboard` is doing, but I don't have time to investigate that further, sorry.

**Comment by taigacute** [comment]
@purcell  ok .i had ask for dashboard.

**Comment by taigacute** [comment]
@purcell   hi  i use the minal config reproduce this problem , i only install the `page-break-lines`
```
(package-initialize)

; (load-file (concat (file-name-directory user-emacs-directory)
	; "core/core-load-paths.el"))
(setq use-package-always-ensure t)


(defun hardcore/init-use-package ()
  (setq package-archives'(("melpa" . "http://elpa.emacs-china.org/melpa/")
                          ("gnu" . "http://elpa.emacs-china.org/gnu/")))

  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
  (eval-when-compile
  (require 'use-package))
  (setq use-package-always-ensure t)
  (use-package use-package-ensure-system-package))

(hardcore/init-use-package)

  (use-package page-break-lines
    :ensure t)

;; init.el ends here

```

this gif can show problem

![git](https://user-images.githubusercontent.com/41671631/62835629-3fe69f00-bc8d-11e9-90a9-bc8c15c834e1.gif)
