### ISSUE TITLE
Something funky setting global-page-break-lines-mode via Customize

### ISSUE THREAD

**Issue by rnkn** [purcell/page-break-lines#27]
Hi Steve,

Something weird happens when setting global-page-break-lines mode to t via Customize. This is what goes into my custom-file:

    '(global-page-break-lines-mode t nil (page-break-lines))

when I would expect:

    '(global-page-break-lines-mode t)

The problem this causes is if page-break-lines happens *not* to be in the load-path for whatever reason (testing something, etc.) then Emacs initialisation will stumble, with:

    file-missing "Cannot open load file" "No such file or directory" "page-break-lines"

Having a look at the source, I can't see why this is the case, so I suspect that it might be a "clever" change upstream with Emacs... What's your take?

**Comment by purcell** [comment]
I can only imagine that your custom file is getting loaded before packages have been initialized, ie. the various packages' source directories have not yet been added to `load-path` at the time that your `custom-file` gets loaded.

**Comment by purcell** [comment]
> The problem this causes is if page-break-lines happens _not_ to be in the load-path for whatever reason (testing something, etc.) then Emacs initialisation will stumble, with:

FWIW, I get the same clause written into my custom file if I do the same thing. It's normal that *something* would not work as expected if the customize system tries to set things that don't yet exist, so a noisy error like this is a good thing IMO.

**Comment by rnkn** [comment]
I'm calling package-initialize before loading custom-file, so that's not it:
https://github.com/rnkn/.config/blob/master/emacs/init.el

It's more than a noisy error, as it prevents Emacs from loading. The customize system is specifically designed not to prevent loading even when libraries aren't found, e.g. settings hang around after uninstalling their library, because obviously it makes sense if the user then chooses to reinstall. The separation of settings and source is a good thing, and ought not to trip Emacs over.

However I have become convinced this is an Emacs bug. Just wanted to get your take.

**Comment by purcell** [comment]
Yes, you could be right. If I save the setting (producing the same clause in my `custom-file` and then restart Emacs, I see no error. This is with Emacs 26.3.

**Comment by rnkn** [comment]
This appears to be fixed on 27.x
🎉

**Comment by purcell** [comment]
Thanks for confirming.

**Comment by rnkn** [comment]
I'm sorry, I spoke too soon...

I was using MELPA stable, and so I couldn't reproduce the issue with page-break-lines 0.11. Now using your master branch I'm getting the previous results with the init-stopping error. This would seem to indicate the change between 0.11 and master branch of:

https://github.com/purcell/page-break-lines/compare/0.11...master#diff-8890ac1a654e87e2a8fdbe3132883f80R173

is the source of the error. So, the problem appears to be in `define-globalized-minor-mode` and so an Emacs bug...

**Comment by rnkn** [comment]
Just to confirm, yes it is the line https://github.com/purcell/page-break-lines/blob/master/page-break-lines.el#L173

With:
~~~elisp
 '(global-page-break-lines-mode t nil (page-break-lines))
~~~
Without:
~~~elisp
 '(global-page-break-lines-mode t)
~~~

**Comment by rnkn** [comment]
Reported: http://debbugs.gnu.org/cgi/bugreport.cgi?bug=38843

**Comment by purcell** [comment]
Aha. Excellent upstream bug report, btw!
