### ISSUE TITLE
Autoloading customizable variables

### ISSUE THREAD

**Issue by muffinmad** [purcell/page-break-lines#30]
Hi!

Is it necessary to autoload customizable variables?

I'm loading custom-file in `early-init.el` before packages are loaded.
Later value of the `page-break-lines-modes` is overridden by default value on package being loaded.

Removing `autoload` from variables resolve issue for me.

Thanks!

**Comment by purcell** [comment]
That's weird because the autoloads entry looks like

```el
(defvar page-break-lines-modes '(emacs-lisp-mode lisp-mode scheme-mode compilation-mode outline-mode help-mode) "\
Modes in which to enable `page-break-lines-mode'.")
```

and `defvar` has no effect if the variable is already bound. I feel like something else must be going on here. Perhaps try confirming that the var is set to your desired value after the custom file has been loaded.

**Comment by muffinmad** [comment]
Let's start from `emacs -Q`:

1. <kbd>M-:</kbd> `(custom-set-variables '(page-break-lines-modes '(text-mode)))`
2. <kbd>M-:</kbd> `(package-initialize)`
3. <kbd>C-h v</kbd> `page-break-lines-modes`

```
page-break-lines-modes is a variable defined in ‘page-break-lines-autoloads.el’.
Its value is
(emacs-lisp-mode lisp-mode scheme-mode compilation-mode outline-mode help-mode)
```

Don't sure how `defvar` is checking if variable is void but variable is not bound after `custom-set-variables`:
1. <kbd>M-:</kbd> `(custom-set-variables '(page-break-lines-modes '(text-mode)))`
2. <kbd>M-:</kbd> `(boundp 'page-break-lines-modes)` => `nil`

Instead of just `;;;autoload` this code can be used to autoload user option:

```elisp
(defcustom page-break-lines-modes
  '(emacs-lisp-mode lisp-mode scheme-mode compilation-mode outline-mode help-mode)
  "Modes in which to enable `page-break-lines-mode'."
  :type '(repeat symbol)
  :group 'page-break-lines)
;;;###autoload(custom-autoload 'page-break-lines-modes "page-break-lines" t)
```

Then after `custom-set-variables` and `package-initialize`:
```
page-break-lines-modes is a variable defined in ‘page-break-lines.el’.
Its value is (text-mode)
Original value was 
(emacs-lisp-mode lisp-mode scheme-mode compilation-mode outline-mode help-mode)
```

Though [elisp manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/When-to-Autoload.html) says
> Don't autoload a user option just so that a user can set it.

**Comment by purcell** [comment]
Ah, so it's still getting the right value. Yeah, the mechanism behind `custom-set-variables` is quite obscure. In any case, I'm happy to removed the `autoload` because I agree it's unnecessary.

**Comment by purcell** [comment]
I've removed it. It came in as a PR at some previous point, but I can't currently think of a reason to keep it.
