### ISSUE TITLE
Cannot compile with latest emacs

### ISSUE THREAD

**Issue by laynor** [purcell/page-break-lines#33]
The `when` parameter is now mandatory.
https://github.com/purcell/page-break-lines/blob/34cd91d841e5334c6966e25fbfd971a2dfbcee69/page-break-lines.el#L109

See 
https://github.com/emacs-mirror/emacs/commit/32c6732d16385f242b1109517f25e9aefd6caa5c

**Comment by purcell** [comment]
Thanks, pushed a fix.

**Comment by laynor** [comment]
Thank you!
