### ISSUE TITLE
Incompatibility with display-line-numbers-mode (edge case)

### ISSUE THREAD

**Issue by jumper047** [purcell/page-break-lines#39]
When I'm opening some file containing ^L symbols here and there on line 500, everything goes well.  Then I scroll down to line 1000 and last dash in line moves to the next line, because now column with line numbers wider than before, and number of dashes needed to build up the line is the same.

**Comment by jakewilliami** [comment]
Possibly related to #37

**Comment by purcell** [comment]
Yes, this is indeed the same.
