### ISSUE TITLE
Latest update leads to crash on mac os gui

### ISSUE THREAD

**Issue by articuluxe** [purcell/page-break-lines#41]
I run emacs 29.2 on 2 macs: one running Sonoma 14.2.1, the other Monterey 12.7.2.  On both these machines (but not my Linux machine), after updating to the latest page-break-lines (commit e8bfd1a), and launching the emacs server, I would get crashes soon after launching the client frame to connect to the server.  

The stack trace showed 
> EXC_BAD_ACCESS (SIGABRT)
in 
> QuartzCore: CA::Layer::property_did_change(CA::Transaction*, unsigned int) + 4171

There was also the following error:

> page-break-lines--update-display-tables: Arithmetic error during redisplay: <snip my current frame here> signaled (arith-error) [2 times]

After reverting that commit the behavior went away immediately.

I hope this helps someone track down this issue if it happens to them.

**Comment by purcell** [comment]
Thanks for reporting this. That's quite a weird issue, and sounds like an Emacs bug tbh. I'm on the same macOS version but with 29.1, and haven't had any issues, though I don't usually run Emacs in server/client: I just tried it now, both with terminal and GUI frames without issue. What Emacs build do you have? (Homebrew? Railwaycat? Emacsformacosx etc.)

The `arith-error` suggests that `(string-pixel-width (make-string 100 ?a))` is returning zero somewhere — could you try evaluating it in a client frame, or set `debug-on-error` to `t` and see if you can get a backtrace?

I'm happy to commit a workaround or revert the commit but it'd be nice to learn more about what's going on.

**Comment by purcell** [comment]
I repeated my test with Emacs 29.2 btw, and still can't reproduce the issue. So answers to the questions above would help.

**Comment by toinfty** [comment]
I have this issue too. The reason is that the following code segment at https://github.com/purcell/page-break-lines/blob/e8bfd1ab660030679163f5a4913ff24b99095436/page-break-lines.el#L129C46-L130C92 returns `0`.
```emacs-lisp
(/ (string-pixel-width (make-string 100 page-break-lines-char))
    (string-pixel-width (make-string 100 ?a)))
```

Changing it to 
```emacs-lisp
(/ (float (string-pixel-width (make-string 100 page-break-lines-char)))
   (string-pixel-width (make-string 100 ?a)))
```
fixes my issue.

**Comment by purcell** [comment]
Aha! Thanks for providing the detailed info. I had missed that this was integer division, since for me the two widths are the same. This is much less of a mystery, and I'll commit your fix immediately.
