### ISSUE TITLE
MELPA code doesn't match?

### ISSUE THREAD

**Issue by matthewpersico** [purcell/page-break-lines#42]
I updated to 29.2 and ended up grabbing a new version of this package. Using it, I get `Arithmetic error` when trying to load files. So, I took a look at my setup:
```diff
$ diff ./elpa-27.2/page-break-lines-20230804.658/page-break-lines.el ./elpa-29.2/page-break-lines-20240117.1610
8c8
< ;; Package-Requires: ((emacs "24.4"))
---
> ;; Package-Requires: ((emacs "25.1"))
128,138c128,132
<               (let* ((cwidth (char-width page-break-lines-char))
<                      (wwidth-pix (- (window-width nil t)
<                                     (if (and (bound-and-true-p display-line-numbers)
<                                              (fboundp 'line-number-display-width))
<                                         (line-number-display-width t)
<                                       0)))
<                      (width (- (/ wwidth-pix (frame-char-width) cwidth)
<                                (if (display-graphic-p) 0 1)))
<                      (width (if page-break-lines-max-width
<                                 (min width page-break-lines-max-width)
<                               width))
---
>               (let* ((char-relative-width (if (fboundp 'string-pixel-width)
>                                               (/ (string-pixel-width (make-string 100 page-break-lines-char))
>                                                  (string-pixel-width (make-string 100 ?a)))
>                                             (char-width page-break-lines-char)))
>                      (width (floor (window-max-chars-per-line) char-relative-width))
```
So I then came back to this repo to look at 

0.14 - https://github.com/purcell/page-break-lines/blob/69caea070379f3324c530e96e06625c3cd097cb9/page-break-lines.el#L128
0.15 - https://github.com/purcell/page-break-lines/blob/c4283f580fa4feeb9abcaebb99709007db0a3159/page-break-lines.el#L128

Neither of those entries has the updated code from above. How did that get into MELPA and from WHERE????

**Comment by purcell** [comment]
MELPA is always snapshots from the default branch on github, so it's not unlikely that the snapshot versions you've installed differ from the specific tagged versions you linked to.

**Comment by matthewpersico** [comment]
> MELPA packages (in contrast to MELPA Stable packages) are always snapshots from the default branch on github, so it's fairly inevitable that the snapshot versions you're installing will differ from the specific tagged versions you linked to.

But that's where I am confused. The code on your default branch doesn't have that change either: https://github.com/purcell/page-break-lines/blob/master/page-break-lines.el

What am I not understanding?

**Comment by matthewpersico** [comment]
> I think the issue you've encountered is #41, but the reporter hasn't replied to my questions, and I can't reproduce the issue myself on Emacs 29.2. Perhaps you could add more info to that other issue?

I'll see if I can grab a spare few minutes...

**Comment by purcell** [comment]
> The code on your default branch doesn't have that change either: https://github.com/purcell/page-break-lines/blob/master/page-break-lines.el

The code in green in your diff at top here is the code in the latest commit on master, [here](https://github.com/purcell/page-break-lines/blob/e8bfd1ab660030679163f5a4913ff24b99095436/page-break-lines.el#L128-L132). So the `page-break-lines-20240117.1610` package you have installed from MELPA contains exactly the current code from `master` in this repo, and it's therefore not clear to me what the perceived issue is, sorry.

**Comment by matthewpersico** [comment]
I misread something somewhere. MELPA == master. Sorry for the noise. Maybe I can carry on with debugging on the other issue.

**Comment by purcell** [comment]
Thanks. I've got a guesswork-based patch waiting for the other issue, but I'd really prefer to understand what's going wrong, and a backtrace would help.

**Comment by matthewpersico** [comment]
> Thanks. I've got a guesswork-based patch waiting for the other issue, but I'd really prefer to understand what's going wrong, and a backtrace would help.

Not well versed in debugging. Will `(setq etrace-debug 1)` someplace in my `init.el` do the trick?

**Comment by purcell** [comment]
You can either `M-x toggle-debug-on-error` before triggering it interactively, or add `(setq debug-on-error t)` in your init file. Then when it fails (with the arith-error) you should get a `Backtrace` buffer, the contents of which should help me see what's going on. Also useful: your Emacs version, the corresponding startup snippet (ie. how you enable `page-break-lines`), plust how you start Emacs (e.g. `emacs --daemon`, or via the GUI app).
