### ISSUE TITLE
how to define ^L with comment

### ISSUE THREAD

**Issue by futurist** [purcell/page-break-lines#9]
In some white space clean mode, they don't allow special char and clean them up, include ^L char.

How to define ^L after a comment while as still keep the function of page break? That's to say `//^L` in Javascript as a whole to prevent clean up by some formatting lib.

**Comment by purcell** [comment]
What program or code is cleaning up the whitespace? If it cleans up `^L`, wouldn't it also clean up `//^L` to `//`? There's not really any way I can see to handle this in `page-break-lines`.

**Comment by futurist** [comment]
It's [standard-format](https://github.com/maxogden/standard-format) for Javascript code, I'm sending the  whole buffer into that formatting and then get back. It will do some AST and ignore any independent `^L` char, but not `//^L`

**Comment by futurist** [comment]
Will try to found a way to transform `^L` to keep that. seems `page-break-lines` can do nothing about this. Thank you!
